export const COMMERCIAL_AI_COPY_PROHIBITED_PHRASES = [
  'frete grátis',
  'cupom',
  'estoque',
  'últimas unidades',
  'só hoje',
  'corre',
  'acaba hoje',
  'tempo limitado',
  'menor preço',
  'preço histórico',
  'garantia',
  'garantido',
  'original',
  'autêntico',
  'loja oficial',
  'vendedor oficial',
  'cashback',
  'desconto extra',
  'entrega hoje',
  'entrega garantida',
  'mais vendido',
  'número um',
  'exclusivo',
  'aproveite antes que acabe',
  'oportunidade única',
] as const;
